### PR TITLE
fix wording in Beta preferences pane

### PR DESCRIPTION
**Pull request by tessus**
I've added the word `from` to items 2 and 3, otherwise the action would mean to delete the entire history.
But what actually meant is that the current/selected item is removed from the history.

### CODE REVIEW

**Comment by tessus** [comment]
@ianhu did you see my comment? It would be great, if you could add that before you create a new release.
Unless the text really means what it says and it deletes the entire history.

**Comment by tessus** [comment]
@ian4hu did you see my comment? It would be great, if you could add that before you create a new release.
Unless the text really means what it says and it deletes the entire history.

(I had to delete the comment and add it again, because I mentioned the wrong person)

**Comment by ian4hu** [comment]
I will review it later. The wording issue is not only in .xib file, but also in i18n .strings file.

**Comment by tessus** [comment]
@ian4hu I'm sorry, I don't know how to update the string files. I guess you mean the file `CPYBetaPreferenceViewController.strings` in the different language directories.
I remember there was a way to update them automatically, but I can't figure it out. I forgot.

**Comment by tessus** [comment]
@ian4hu may I ask how you updated the other files? Did you do it manually or is there a Xcode tool to automatically update the other files? I mean this part `/* Class = "NSButtonCell"; title = "Paste and delete from history"; ObjectID = "M5n-Mr-02l"; */`

**Comment by ian4hu** [comment]
> @ian4hu may I ask how you updated the other files? Did you do it manually or is there a Xcode tool to automatically update the other files? I mean this part `/* Class = "NSButtonCell"; title = "Paste and delete from history"; ObjectID = "M5n-Mr-02l"; */`

Execute the build command from Xcode > Product > Build menu item will trigger `BartyCrouch`'s  Build Phase, and then the `BartyCrouch` update the other files automaticly (only the original text, the translated text is untouched).

image

**Comment by tessus** [comment]
Thx, for the info. I hoped that was an Xcode feature, but I guess Apple didn't think that far ahead....

**Pull request merged**
